# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ayamir/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ayamir/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayamir/CLionProjects/ConvertImage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayamir/CLionProjects/ConvertImage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ayamir/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ayamir/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayamir/CLionProjects/ConvertImage/CMakeFiles /home/ayamir/CLionProjects/ConvertImage//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayamir/CLionProjects/ConvertImage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

#=============================================================================
# Target rules for targets named ConvertImage

# Build rule for target.
ConvertImage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConvertImage
.PHONY : ConvertImage

# fast build rule for target.
ConvertImage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/build
.PHONY : ConvertImage/fast

ConvertImage.o: ConvertImage.cpp.o

.PHONY : ConvertImage.o

# target to build an object file
ConvertImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/ConvertImage.cpp.o
.PHONY : ConvertImage.cpp.o

ConvertImage.i: ConvertImage.cpp.i

.PHONY : ConvertImage.i

# target to preprocess a source file
ConvertImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/ConvertImage.cpp.i
.PHONY : ConvertImage.cpp.i

ConvertImage.s: ConvertImage.cpp.s

.PHONY : ConvertImage.s

# target to generate assembly for a file
ConvertImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/ConvertImage.cpp.s
.PHONY : ConvertImage.cpp.s

IConvertImage.o: IConvertImage.cpp.o

.PHONY : IConvertImage.o

# target to build an object file
IConvertImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/IConvertImage.cpp.o
.PHONY : IConvertImage.cpp.o

IConvertImage.i: IConvertImage.cpp.i

.PHONY : IConvertImage.i

# target to preprocess a source file
IConvertImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/IConvertImage.cpp.i
.PHONY : IConvertImage.cpp.i

IConvertImage.s: IConvertImage.cpp.s

.PHONY : IConvertImage.s

# target to generate assembly for a file
IConvertImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConvertImage.dir/build.make CMakeFiles/ConvertImage.dir/IConvertImage.cpp.s
.PHONY : IConvertImage.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ConvertImage"
	@echo "... Test"
	@echo "... ConvertImage.o"
	@echo "... ConvertImage.i"
	@echo "... ConvertImage.s"
	@echo "... IConvertImage.o"
	@echo "... IConvertImage.i"
	@echo "... IConvertImage.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

